name: Generate Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # Chạy tự động hàng ngày lúc 00:00 UTC
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}

      - name: Commit and Push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout main  # Đảm bảo đang ở đúng branch
          git pull --rebase origin main || true  # Lấy thay đổi mới nhất
          git add -A
          git diff --quiet && echo "No changes to commit" || (git commit -m "Update profile summary cards" && git push origin HEAD:main)
